# "docker-compose up" to start the services
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    networks:
      - db-network
  app: &base
    container_name: app
    depends_on:
      - "mongo"
    restart: unless-stopped # Always restart the container unless it is stopped
    ports:
      - "5000:5000" # Publish the port 5000 for the server
    environment:
      - DB_URI=mongo # Use the Docker DNS to resolve the ip of mongo container
    build: . # Build the server at start
    networks:
      - db-network
  client:
    <<: *base
    container_name: client
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      - NODE_ENV=development # required to get nodemon working
      - DB_URI=mongo
    volumes: # these volume mount greatly speed up the build time
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules' # allowing access to host directory node_modules
      - '/usr/src/app/client/node_modules' # allowing access to client node_modules
    command: sh -c "npm install && npm run client-install && npm run dev" # overriding dockerfile command to install client

volumes:
  db-data: {}
networks:
  db-network:
    driver: bridge
